select * from customer limit 20
--what is the total revenue generated by men vs women ?
Select gender,sum(purchase_amount) as revenue
from customer
group by gender
--which customers used discountcode but still spent more than avg purchase amount ?
select customer_id, purchase_amount
from customer 
where discount_applied='Yes' and purchase_amount>=(select AVG(purchase_amount)from customer)
--what are the top5 products with highest average review rating ?
select  item_purchased ,round(avg(review_rating::numeric),2) as "avg_product_rating"
from customer 
group by item_purchased
order by avg(review_rating) desc
--which location the purchase is more?
SELECT sum(purchase_amount) AS purchase_sum, location
FROM customer
GROUP BY location 
Order by sum(purchase_amount) desc;
--compare avg purchases between shipping methods ?
select shipping_type,round(avg(purchase_amount::numeric),2) as purchase_avg
from customer
group by shipping_type
order by purchase_avg desc ;
-- which size clothes are sold more ?
SELECT size, COUNT(*) AS total_items_sold
FROM customer
GROUP BY size
ORDER BY total_items_sold DESC;
--customers with subscription brough more or with no subscription ? and also compare average spend between them also 
Select subscription_status ,round(avg(purchase_amount),2)as avg,round(sum(purchase_amount),2)as sum, count(*) as total_items_sold
from customer 
group by subscription_status 
--Top 5 products have highest percentage of purchases with discounts applied 
SELECT  item_purchased, 
ROUND(100* SUM(CASE when discount_applied = 'Yes'then 1 else 0 END)/ count(*) ,2) as percentage
from customer 
group by item_purchased
order by percentage desc
limit 5;
--differentiate customers into new ,Returning,and loyal based on their total number of previous purchases and show count of each segment
With customer_type as
(
Select customer_id,previous_purchases,
CASE when previous_purchases=1 then 'new'
     when previous_purchases between 2 and 10 then 'returning'
	 else 'loyal'
	 end as customer_segment
from customer
)
select customer_segment , count(*) as "number_of_customers"
from customer_type
group by customer_segment
--top 3 items in each category 
with item_counts as
(
select category,item_purchased,count(customer_id)as total_orders,
row_number() over(partition by category order by count(customer_id)desc)as item_rank
from customer 
group by category, item_purchased
)
select item_rank , category , item_purchased, total_orders
from item_counts
where item_rank <=3;



--are customers who are repeat buyers are most likely to subscribe ?
select subscription_status , count(customer_id) as repeat_buyers 
from customer 
where previous_purchases >5
group by subscription_status 

--what is the revenue contribution of each age group ?
select age_group , sum(purchase_amount) as total
from customer 
group by age_group 
order by total desc;
